name: test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["luajit-2.1", "5.4", "5.5"]
    env:
      MOONBUG_TEST: "1"
      MOONBUG_LOG: "off"
      NO_COLOR: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: ${{ matrix.lua_version }}
      - uses: leafo/gh-actions-luarocks@v6
      - name: install dependencies
        run: |
          luarocks install lua-cjson
          luarocks install luacov
          luarocks install luasocket
      - uses: Homebrew/actions/setup-homebrew@main
      - name: Lua Language Server Check
        run: |
          brew install lua-language-server
          luarocks install llscheck
          llscheck
      - name: run tests
        run: |
          if command -v lua > /dev/null 2>&1; then LUA=lua; else LUA=luajit; fi
          "$LUA" -v
          MOONBUG_LUA="$LUA" "$LUA" -lluacov ./tests/run.lua
